import type { ClusterMap3D, ClusterEntry3D, Point3D } from '../dla-3d';

interface TreeNode {
  key: string;
  point: Point3D;
  children: TreeNode[];
}

export function extractPaths(cluster: ClusterMap3D): Point3D[][] {
  if (Object.keys(cluster).length === 0) return [];

  const childrenMap = buildChildrenMap(cluster);
  const paths: Point3D[][] = [];

  for (const [key, entry] of Object.entries(cluster)) {
    if (entry.parentPoint !== null) continue;
    const rootNode = buildTree(key, entry, childrenMap, cluster);
    collectPaths(rootNode, [rootNode.point], paths);
  }

  return paths;
}

export function generateBlenderScript(paths: Point3D[][]): string {
  const lines: string[] = [
    '# DLA 3D Export — generated by dla-sim',
    '# Open this file in Blender\'s Scripting tab and click Run.',
    '',
    'import bpy',
    '',
    'curve_data = bpy.data.curves.new("DLA_Paths", "CURVE")',
    'curve_data.dimensions = "3D"',
    '',
  ];

  for (let i = 0; i < paths.length; i++) {
    const path = paths[i];
    if (path.length < 2) continue;

    lines.push(`spline = curve_data.splines.new("NURBS")`);
    lines.push(`spline.points.add(${path.length - 1})`);
    lines.push(`spline.use_endpoint_u = True`);

    const coords = path
      .map((p) => `(${p.x}, ${p.y}, ${p.z}, 1)`)
      .join(', ');
    lines.push(`coords = [${coords}]`);
    lines.push('for j, co in enumerate(coords):');
    lines.push('    spline.points[j].co = co');
    lines.push('');
  }

  lines.push('obj = bpy.data.objects.new("DLA_Paths", curve_data)');
  lines.push('bpy.context.collection.objects.link(obj)');
  lines.push('bpy.context.view_layer.objects.active = obj');
  lines.push('obj.select_set(True)');
  lines.push('');

  return lines.join('\n');
}

function buildChildrenMap(
  cluster: ClusterMap3D,
): Map<string, string[]> {
  const children = new Map<string, string[]>();

  for (const [key, entry] of Object.entries(cluster)) {
    if (!entry.parentPoint) continue;
    const parentKey = pointKey(entry.parentPoint);
    let list = children.get(parentKey);
    if (!list) {
      list = [];
      children.set(parentKey, list);
    }
    list.push(key);
  }

  return children;
}

function buildTree(
  key: string,
  entry: ClusterEntry3D,
  childrenMap: Map<string, string[]>,
  cluster: ClusterMap3D,
): TreeNode {
  const childKeys = childrenMap.get(key) ?? [];
  const childNodes = childKeys
    .filter((k) => cluster[k])
    .map((k) => buildTree(k, cluster[k], childrenMap, cluster));

  return { key, point: entry.point, children: childNodes };
}

function collectPaths(
  node: TreeNode,
  currentPath: Point3D[],
  result: Point3D[][],
): void {
  if (node.children.length === 0) {
    if (currentPath.length >= 2) {
      result.push([...currentPath]);
    }
    return;
  }

  if (node.children.length === 1) {
    currentPath.push(node.children[0].point);
    collectPaths(node.children[0], currentPath, result);
    return;
  }

  // Branch point: end current path here and start new paths for each child
  if (currentPath.length >= 2) {
    result.push([...currentPath]);
  }

  for (const child of node.children) {
    collectPaths(child, [node.point, child.point], result);
  }
}

function pointKey(p: Point3D): string {
  return `${p.x.toFixed(4)},${p.y.toFixed(4)},${p.z.toFixed(4)}`;
}
