import type { ClusterMap3D, ClusterEntry3D, Point3D } from "../dla-3d";

interface TreeNode {
  key: string;
  point: Point3D;
  children: TreeNode[];
}

export function extractPaths(cluster: ClusterMap3D): Point3D[][] {
  if (Object.keys(cluster).length === 0) return [];

  const childrenMap = buildChildrenMap(cluster);
  const paths: Point3D[][] = [];

  for (const [key, entry] of Object.entries(cluster)) {
    if (entry.parentPoint !== null) continue;
    const rootNode = buildTree(key, entry, childrenMap, cluster);
    collectPaths(rootNode, [rootNode.point], paths);
  }

  return paths;
}

export function generateBlenderScript(paths: Point3D[][]): string {
  const lines: string[] = [
    "# DLA 3D Export — generated by dla-sim",
    "# Open this file in Blender's Scripting tab and click Run.",
    "",
    "import bpy",
    "",
    'curve_data = bpy.data.curves.new("DLA_Paths", "CURVE")',
    'curve_data.dimensions = "3D"',
    "",
  ];

  for (let i = 0; i < paths.length; i++) {
    const path = paths[i];
    if (path.length < 2) continue;

    lines.push(`spline = curve_data.splines.new("NURBS")`);
    lines.push(`spline.points.add(${path.length - 1})`);
    lines.push(`spline.use_endpoint_u = True`);

    const coords = path.map((p) => `(${p.x}, ${p.y}, ${p.z}, 1)`).join(", ");
    lines.push(`coords = [${coords}]`);
    lines.push("for j, co in enumerate(coords):");
    lines.push("    spline.points[j].co = co");
    lines.push("");
  }

  lines.push('obj = bpy.data.objects.new("DLA_Paths", curve_data)');
  lines.push("bpy.context.collection.objects.link(obj)");
  lines.push("bpy.context.view_layer.objects.active = obj");
  lines.push("obj.select_set(True)");
  lines.push("");

  return lines.join("\n");
}

function buildChildrenMap(cluster: ClusterMap3D): Map<string, string[]> {
  const children = new Map<string, string[]>();

  for (const [key, entry] of Object.entries(cluster)) {
    if (!entry.parentPoint) continue;
    const parentKey = pointKey(entry.parentPoint);
    let list = children.get(parentKey);
    if (!list) {
      list = [];
      children.set(parentKey, list);
    }
    list.push(key);
  }

  return children;
}

function buildTree(
  key: string,
  entry: ClusterEntry3D,
  childrenMap: Map<string, string[]>,
  cluster: ClusterMap3D,
): TreeNode {
  const childKeys = childrenMap.get(key) ?? [];
  const childNodes = childKeys
    .filter((k) => cluster[k])
    .map((k) => buildTree(k, cluster[k], childrenMap, cluster));

  return { key, point: entry.point, children: childNodes };
}

function collectPaths(
  node: TreeNode,
  currentPath: Point3D[],
  result: Point3D[][],
): void {
  if (node.children.length === 0) {
    if (currentPath.length >= 2) {
      result.push([...currentPath]);
    }
    return;
  }

  if (node.children.length === 1) {
    currentPath.push(node.children[0].point);
    collectPaths(node.children[0], currentPath, result);
    return;
  }

  // Branch point: end current path here and start new paths for each child
  if (currentPath.length >= 2) {
    result.push([...currentPath]);
  }

  for (const child of node.children) {
    collectPaths(child, [node.point, child.point], result);
  }
}

export function generateVisualBlenderScript(cluster: ClusterMap3D): string {
  const entries = Object.values(cluster);
  if (entries.length === 0) return "";

  const sphereData: string[] = [];
  const edgeVerts: string[] = [];
  const edges: string[] = [];
  let vertIdx = 0;

  for (const entry of entries) {
    const { x, y, z } = entry.point;
    const d = entry.distance;
    const hue = d === 0 ? 0 : (d * 30) % 360;
    const sat = d === 0 ? 0.0 : 0.8;
    const light = d === 0 ? 1.0 : 0.55;
    sphereData.push(`(${x}, ${y}, ${z}, ${hue}, ${sat}, ${light})`);

    if (entry.parentPoint) {
      const p = entry.parentPoint;
      edgeVerts.push(`(${x}, ${y}, ${z})`);
      edgeVerts.push(`(${p.x}, ${p.y}, ${p.z})`);
      edges.push(`(${vertIdx}, ${vertIdx + 1})`);
      vertIdx += 2;
    }
  }

  const lines: string[] = [
    "# DLA 3D Visual Export — generated by dla-sim",
    "# Open this file in Blender's Scripting tab and click Run.",
    "",
    "import bpy",
    "import colorsys",
    "",
    "def hsl_to_rgb(h, s, l):",
    "    return colorsys.hls_to_rgb(h / 360.0, l, s)",
    "",
    "mat_cache = {}",
    "",
    "def get_material(h, s, l):",
    "    key = (h, s, l)",
    "    if key in mat_cache:",
    "        return mat_cache[key]",
    '    r, g, b = hsl_to_rgb(h, s, l)',
    '    mat = bpy.data.materials.new(name=f"DLA_mat_{h}_{s}_{l}")',
    "    mat.use_nodes = True",
    '    bsdf = mat.node_tree.nodes["Principled BSDF"]',
    '    bsdf.inputs["Base Color"].default_value = (r, g, b, 1.0)',
    "    mat_cache[key] = mat",
    "    return mat",
    "",
    'collection = bpy.data.collections.new("DLA_Visual")',
    "bpy.context.scene.collection.children.link(collection)",
    "",
    `sphere_data = [${sphereData.join(", ")}]`,
    "",
    "for i, (x, y, z, h, s, l) in enumerate(sphere_data):",
    '    mesh = bpy.data.meshes.new(f"DLA_sphere_{i}")',
    '    obj = bpy.data.objects.new(f"DLA_sphere_{i}", mesh)',
    "    collection.objects.link(obj)",
    "    bpy.context.view_layer.objects.active = obj",
    "    obj.select_set(True)",
    "    bpy.ops.object.select_all(action='DESELECT')",
    "    obj.select_set(True)",
    "    bpy.context.view_layer.objects.active = obj",
    "    bpy.ops.mesh.primitive_uv_sphere_add(radius=0.12, segments=8, ring_count=8, location=(x, y, z))",
    "    sphere_obj = bpy.context.active_object",
    '    sphere_obj.name = f"DLA_node_{i}"',
    "    old_collections = list(sphere_obj.users_collection)",
    "    for c in old_collections:",
    "        c.objects.unlink(sphere_obj)",
    "    collection.objects.link(sphere_obj)",
    "    mat = get_material(h, s, l)",
    "    sphere_obj.data.materials.append(mat)",
    "    bpy.data.objects.remove(obj)",
    "    bpy.data.meshes.remove(mesh)",
    "",
  ];

  if (edgeVerts.length > 0) {
    lines.push(`verts = [${edgeVerts.join(", ")}]`);
    lines.push(`edges = [${edges.join(", ")}]`);
    lines.push('line_mesh = bpy.data.meshes.new("DLA_Lines")');
    lines.push("line_mesh.from_pydata(verts, edges, [])");
    lines.push("line_mesh.update()");
    lines.push('line_obj = bpy.data.objects.new("DLA_Lines", line_mesh)');
    lines.push("collection.objects.link(line_obj)");
    lines.push('line_mat = bpy.data.materials.new(name="DLA_line_mat")');
    lines.push("line_mat.use_nodes = True");
    lines.push('bsdf = line_mat.node_tree.nodes["Principled BSDF"]');
    lines.push(
      'bsdf.inputs["Base Color"].default_value = (0.4, 0.667, 1.0, 1.0)',
    );
    lines.push('bsdf.inputs["Alpha"].default_value = 0.6');
    lines.push("line_mat.blend_method = 'BLEND'");
    lines.push("line_obj.data.materials.append(line_mat)");
    lines.push("");
  }

  lines.push('print("DLA Visual export complete.")');
  lines.push("");

  return lines.join("\n");
}

function pointKey(p: Point3D): string {
  return `${p.x.toFixed(4)},${p.y.toFixed(4)},${p.z.toFixed(4)}`;
}
