import React from 'react';
import './about.css';

const About: React.FC = () => {
  return (
    <div className="dlasim-about-container">
      <div className="dlasim-about-content">
        
        <h1 className="dlasim-about-title">
            Difussion-Limited Aggregation Studio
        </h1>
        
        <p className="dlasim-about-version">Version 0.0.1</p>
        
        <div className="dlasim-about-image-container">
          <img 
            src="/DLA-Studio-2025/example-1.png" 
            alt="DLA Studio Example" 
            className="dlasim-about-image"
          />
        </div>
        
        <div className="dlasim-about-section">
          <h2 className="dlasim-about-section-title">About</h2>
          <p className="dlasim-about-description">
            DLA Studio is an interactive web application for exploring Diffusion-Limited Aggregation (DLA) 
            patterns through various visualization methods. Create, manipulate, and export beautiful 
            fractal-like structures generated by particle aggregation algorithms.
          </p>
        </div>

        <div className="dlasim-about-section">
          <h2 className="dlasim-about-section-title">Features</h2>
          <ul className="dlasim-about-features">
            <li><strong>Simulation:</strong> Interactive 2D DLA simulation with real-time particle generation</li>
            <li><strong>Gradient:</strong> Customizable color gradients for distance-based visualization</li>
            <li><strong>SVG Export:</strong> Generate scalable vector graphics with multiple rendering options</li>
            <li><strong>Tools:</strong> Paint brush, eraser, and shape spawning controls</li>
          </ul>
        </div>

        <div className="dlasim-about-section">
          <h2 className="dlasim-about-section-title">How to Use</h2>
          <ol className="dlasim-about-instructions">
            <li>Start with the <strong>Simulation</strong> tab to generate DLA patterns</li>
            <li>Use the <strong>Gradient</strong> tab to customize color schemes</li>
            <li>Export your creations as SVG files using the <strong>SVG</strong> tab</li>
            <li>Experiment with different tools and settings to create unique patterns</li>
          </ol>
        </div>

        <div className="dlasim-support-section">
            <h2 className="dlasim-about-section-title">Support</h2>
            <p className="dlasim-support-content">
                This is an open source project. Feel free to file issues or pull requests on {" "}
                <a href="https://github.com/chriswininger/DLA-Studio-2025" target="_blank" rel="noopener noreferrer">
                    chriswininger/DLA-Studio-2025
                </a>
            </p>
        </div>

        <div className="dlasim-about-section">
          <h2 className="dlasim-about-section-title">Author</h2>
          <p className="dlasim-about-author">
            Created by Chris Wininger
          </p>
        </div>
      </div>
    </div>
  );
};

export default About; 