import React from 'react';
import { Link } from 'react-router-dom';
import './about.css';

const About: React.FC = () => {
  const schema = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "name": "DLA Studio",
    "applicationCategory": "MultimediaApplication",
    "operatingSystem": "Any",
    "description": "An interactive web application for exploring Diffusion-Limited Aggregation (DLA) patterns. Create, manipulate, and export beautiful fractal-like structures.",
    "author": {
      "@type": "Person",
      "name": "Chris Wininger"
    },
    "url": "https://dla-studio.com",
    "image": "https://dla-studio.com/example-1.png",
    "offers": {
      "@type": "Offer",
      "price": "0"
    }
  };

  return (
    <>
      <title>DLA Studio - About</title>
      <meta name="description" content="Learn about DLA Studio, an interactive web application for exploring Diffusion-Limited Aggregation (DLA) patterns. Create, manipulate, and export beautiful fractal-like structures." />
      <script type="application/ld+json">{JSON.stringify(schema)}</script>
      <div className="dlasim-about-container">
        <div className="dlasim-about-content">
          
          <h1 className="dlasim-about-title">
              Difussion-Limited Aggregation Studio
          </h1>
          
          <p className="dlasim-about-version">Version 0.0.1</p>

          <p>Skip the Readme and start right away with the <Link to="/simple-2d-animated-dla" className="dlasim-about-link">simulation tab</Link></p>

          
          <div className="dlasim-about-image-container">
            <img 
              src="/example-1.png" 
              alt="DLA Studio Example" 
              className="dlasim-about-image"
            />
          </div>
          
          <div className="dlasim-about-section">
            <h2 className="dlasim-about-section-title">About</h2>
            <p className="dlasim-about-description">
              DLA Studio is an interactive web application for exploring Diffusion-Limited Aggregation (DLA) 
              patterns through various visualization methods. Create, manipulate, and export beautiful 
              fractal-like structures generated by particle aggregation algorithms.
            </p>
            
            <div className="dlasim-video-container">
              <iframe
                width="560"
                height="315"
                src="https://www.youtube.com/embed/videoseries?si=jhl8M3o-tlkgjTmc&amp;list=PLIqr6JnjM0Ahbc1NJyz3-LK5b6JK3f2i_"
                title="DLA Tutorial Series"
                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerPolicy="strict-origin-when-cross-origin"
                allowFullScreen>
                </iframe>
              </div>
          </div>

          <div className="dlasim-about-section">
            <h2 className="dlasim-about-section-title">Features</h2>
            <ul className="dlasim-about-features">
              <li><strong>Simulation:</strong> Interactive 2D DLA simulation with real-time particle generation</li>
              <li><strong>Gradient:</strong> Customizable color gradients for distance-based visualization</li>
              <li><strong>SVG Export:</strong> Generate scalable vector graphics with multiple rendering options</li>
              <li><strong>Tools:</strong> Paint brush, eraser, and shape spawning controls</li>
            </ul>
          </div>

          <div className="dlasim-about-section">
            <h2 className="dlasim-about-section-title">How to Use</h2>
            <ol className="dlasim-about-instructions">
              <li>
                <strong>Simulation:</strong> Interactive 2D DLA simulation with real-time particle generation
                <div className="dlasim-video-container">
                  <iframe
                    width="560"
                    height="315"
                    src="https://www.youtube.com/embed/MIBIu0H39nk?si=miRNDiH3tayzfnBM"
                    title="DLA Simulation Tutorial"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowFullScreen
                  ></iframe>
                </div>
              </li>
              <li>
                <strong>Gradient:</strong> Customizable color gradients for distance-based visualization
                <div className="dlasim-video-container">
                  <iframe
                    width="560"
                    height="315"
                    src="https://www.youtube.com/embed/38TUL8L6T4E?si=wg-3DKCCcppwHYMQ"
                    title="DLA Gradient Tutorial"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowFullScreen
                  ></iframe>
                </div>
              </li>
              <li>
                <strong>SVG Export:</strong> Generate scalable vector graphics with multiple rendering options
                <div className="dlasim-video-container">
                  <iframe
                    width="560"
                    height="315"
                    src="https://www.youtube.com/embed/gPpkfmXuFas?si=aKrug0Wqmqe16Bwn"
                    title="DLA SVG Tutorial"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowFullScreen
                  ></iframe>
                </div>
              </li>
            </ol>
          </div>

          <div className="dlasim-support-section">
              <h2 className="dlasim-about-section-title">Support</h2>
              <p className="dlasim-support-content">
                  This is an open source project. Feel free to file issues or pull requests on {" "}
                  <a href="https://github.com/chriswininger/DLA-Studio-2025" target="_blank" rel="noopener noreferrer">
                      chriswininger/DLA-Studio-2025
                  </a>
              </p>
          </div>

          <div className="dlasim-about-section">
            <h2 className="dlasim-about-section-title">Author</h2>
            <p className="dlasim-about-author">
              Created by Chris Wininger
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

export default About; 